# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: jschpp's Blog
email: mail@jschpp.de

description: >
  Stuff I'm thinking about. Stuff I've written. Or just stuff in general.
  But mostly stuff about computers...
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.jschpp.de"
twitter_username: jschpp
github_username:  jschpp

# Build settings
markdown: kramdown

permalink:     date
timezone:      Europe/Berlin

socialmedia:
  - username: jschpp
    link: icon-twitter.html
  - username: jschpp
    link: icon-github.html
  - username: jschpp
    link: icon-facebook.html

menu:
  - name: About
    url: /about/
  - name: Public Keys
    url: /keys/

files: "https://www.jschpp.de/files/"


gems:
  - jekyll-gist
  - jekyll-paginate
