# Site settings
title: jschpp's Blog
email: mail@jschpp.de
description: >
  Stuff I'm thinking about. Stuff I've written. Or just stuff in general.
  But mostly stuff about computers... <br>Private Blog of Johannes Schöpp
baseurl: ""
url: "https://jschpp.de"
repository: "jschpp/jschpp.github.io"
permalink:     date
timezone:      Europe/Berlin

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap

feed:
  path: feed.xml
  excerpt_only: true

menu:
  - name: About
    url: /about/
  - name: Public Keys
    url: /keys/
  - name: Disclaimer
    url: /disclaimer/

files: "/files/"

paginate: 5

jekyll_url: https://jekyllrb.com/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true
      lang: en

include:
  - .well-known